from scrapers.base import BaseScraper

class GlobalEPCMajorsScraper(BaseScraper):
    def __init__(self):
        super().__init__("global_epc_majors", "manual_seed", "epc")
        
        # Curated list of the world's top EPC firms (engineering, procurement, construction)
        self.epc_majors = [
            ("Bechtel", "bechtel.com", "Americas", "USA"),
            ("Fluor Corporation", "fluor.com", "Americas", "USA"),
            ("Jacobs Solutions", "jacobs.com", "Americas", "USA"),
            ("KBR (Kellogg Brown & Root)", "kbr.com", "Americas", "USA"),
            ("McDermott International", "mcdermott.com", "Americas", "USA"),
            ("Black & Veatch", "bv.com", "Americas", "USA"),
            ("Burns & McDonnell", "burnsmcd.com", "Americas", "USA"),
            ("PCL Construction", "pcl.com", "Americas", "Canada"),
            ("SNC-Lavalin (AtkinsRéalis)", "atkinsrealis.com", "Americas", "Canada"),
            ("Stantec", "stantec.com", "Americas", "Canada"),
            ("WSP Global", "wsp.com", "Americas", "Canada"),
            ("Hatch", "hatch.com", "Americas", "Canada"),
            ("Technip Energies", "technipenergies.com", "EMEA", "France"),
            ("TechnipFMC", "technipfmc.com", "EMEA", "UK"),
            ("Saipem", "saipem.com", "EMEA", "Italy"),
            ("Maire Tecnimont", "mairetecnimont.com", "EMEA", "Italy"),
            ("Wood plc", "woodplc.com", "EMEA", "UK"),
            ("Petrofac", "petrofac.com", "EMEA", "UK"),
            ("Aker Solutions", "akersolutions.com", "EMEA", "Norway"),
            ("Subsea 7", "subsea7.com", "EMEA", "UK"),
            ("Royal BAM Group", "bam.com", "EMEA", "Netherlands"),
            ("Boskalis", "boskalis.com", "EMEA", "Netherlands"),
            ("Van Oord", "vanoord.com", "EMEA", "Netherlands"),
            ("Demeyere", "deme-group.com", "EMEA", "Belgium"),
            ("ACS Group", "grupoacs.com", "EMEA", "Spain"),
            ("Ferrovial", "ferrovial.com", "EMEA", "Spain"),
            ("Acciona", "acciona.com", "EMEA", "Spain"),
            ("Sacyr", "sacyr.com", "EMEA", "Spain"),
            ("Vinci", "vinci.com", "EMEA", "France"),
            ("Bouygues Construction", "bouygues-construction.com", "EMEA", "France"),
            ("Eiffage", "eiffage.com", "EMEA", "France"),
            ("Skanska", "skanska.com", "EMEA", "Sweden"),
            ("NCC", "ncc.group", "EMEA", "Sweden"),
            ("Peab", "peab.com", "EMEA", "Sweden"),
            ("Strabag", "strabag.com", "EMEA", "Austria"),
            ("Porr", "porr-group.com", "EMEA", "Austria"),
            ("Bilfinger", "bilfinger.com", "EMEA", "Germany"),
            ("Hochtief", "hochtief.com", "EMEA", "Germany"),
            ("Bauer Group", "bauer.de", "EMEA", "Germany"),
            ("Mott MacDonald", "mottmac.com", "EMEA", "UK"),
            ("Arup", "arup.com", "EMEA", "UK"),
            ("Balfour Beatty", "balfourbeatty.com", "EMEA", "UK"),
            ("Laing O'Rourke", "laingorourke.com", "EMEA", "UK"),
            ("Kier Group", "kier.co.uk", "EMEA", "UK"),
            ("Costain", "costain.com", "EMEA", "UK"),
            ("Larsen & Toubro (L&T)", "larsentoubro.com", "APAC", "India"),
            ("Tata Projects", "tataprojects.com", "APAC", "India"),
            ("Engineers India (EIL)", "engineersindia.com", "APAC", "India"),
            ("Reliance Infrastructure", "rinfra.com", "APAC", "India"),
            ("Megha Engineering (MEIL)", "meil.in", "APAC", "India"),
            ("JGC Holdings", "jgc.com", "APAC", "Japan"),
            ("Chiyoda Corporation", "chiyodacorp.com", "APAC", "Japan"),
            ("Toyo Engineering", "toyo-eng.com", "APAC", "Japan"),
            ("IHI Corporation", "ihi.co.jp", "APAC", "Japan"),
            ("Kajima Corporation", "kajima.co.jp", "APAC", "Japan"),
            ("Obayashi Corporation", "obayashi.co.jp", "APAC", "Japan"),
            ("Shimizu Corporation", "shimz.co.jp", "APAC", "Japan"),
            ("Taisei Corporation", "taisei.co.jp", "APAC", "Japan"),
            ("Takenaka Corporation", "takenaka.co.jp", "APAC", "Japan"),
            ("Samsung Engineering", "samsungengineering.com", "APAC", "South Korea"),
            ("Samsung C&T", "samsungcnt.com", "APAC", "South Korea"),
            ("Hyundai Engineering & Construction", "hdec.kr", "APAC", "South Korea"),
            ("Hyundai Engineering", "hec.co.kr", "APAC", "South Korea"),
            ("GS Engineering & Construction", "gsenc.com", "APAC", "South Korea"),
            ("Daewoo E&C", "daewooenc.com", "APAC", "South Korea"),
            ("DL E&C (Daelim)", "dlenc.co.kr", "APAC", "South Korea"),
            ("SK Ecoplant", "skecoplant.com", "APAC", "South Korea"),
            ("POSCO E&C", "poscoenc.com", "APAC", "South Korea"),
            ("Hanwha Corporation/E&C", "hwenc.com", "APAC", "South Korea"),
            ("China State Construction Engineering (CSCEC)", "cscec.com", "APAC", "China"),
            ("China Railway Construction Corporation (CRCC)", "crcc.cn", "APAC", "China"),
            ("China Railway Group (CREC)", "crec.cn", "APAC", "China"),
            ("China Communications Construction (CCCC)", "en.ccccltd.cn", "APAC", "China"),
            ("Power Construction Corporation of China (PowerChina)", "powerchina.cn", "APAC", "China"),
            ("China Energy Engineering (CEEC)", "ceec.net.cn", "APAC", "China"),
            ("China Metallurgical Group (MCC)", "mcc.com.cn", "APAC", "China"),
            ("Sinopec Engineering", "segroup.cn", "APAC", "China"),
            ("China Petroleum Engineering & Construction (CPECC)", "cpecc.cnpc.com.cn", "APAC", "China"),
            ("CNOOC Engineering", "cnoocengineering.com", "APAC", "China"),
            ("CTCI Corporation", "ctci.com", "APAC", "Taiwan"),
            ("CIMIC Group", "cimic.com.au", "APAC", "Australia"),
            ("Lendlease", "lendlease.com", "APAC", "Australia"),
            ("Worley", "worley.com", "APAC", "Australia"),
            ("Downer Group", "downergroup.com", "APAC", "Australia"),
            ("Clough", "cloughgroup.com", "APAC", "Australia"),
            ("Monadelphous", "monadelphous.com.au", "APAC", "Australia"),
            ("Consolidated Contractors Company (CCC)", "ccc.net", "Middle East", "Greece/UAE"),
            ("Orascom Construction", "orascom.com", "Middle East", "Egypt/UAE"),
            ("The Arab Contractors", "arabcont.com", "Middle East", "Egypt"),
            ("Hassan Allam Holding", "hassanallam.com", "Middle East", "Egypt"),
            ("Petrojet", "petrojet.com.eg", "Middle East", "Egypt"),
            ("Enppi", "enppi.com", "Middle East", "Egypt"),
            ("Galfar Engineering", "galfar.com", "Middle East", "Oman"),
            ("Oman India Fertiliser Company (OMIFCO)", "omifco.com", "Middle East", "Oman"), # Might not be EPC but big
            ("Técnicas Reunidas", "tecnicasreunidas.es", "EMEA", "Spain"),
            ("Audex", "audex.com", "APAC", "Singapore"),
            ("Sembcorp Marine", "sembmarine.com", "APAC", "Singapore"),
            ("Keppel Offshore & Marine", "keppelom.com", "APAC", "Singapore"),
            ("Malaysia Marine and Heavy Engineering (MMHE)", "mhb.com.my", "APAC", "Malaysia"),
            ("Sapura Energy", "sapuraenergy.com", "APAC", "Malaysia"),
            ("Dialog Group", "dialogasia.com", "APAC", "Malaysia")
        ]

    def scrape(self):
        all_companies = []
        for name, domain, region, country in self.epc_majors:
            all_companies.append({
                "name": name,
                "sector": self.sector,
                "sub_sector": "major_contractor",
                "domain": domain,
                "email_1": None,
                "email_2": None,
                "phone": None,
                "country": country,
                "city": None,
                "region": region,
                "employee_count": "5000+",
                "revenue_range": "$1B+",
                "source": self.name,
                "source_url": None,
                "notes": "Top 100 Global EPC Major",
                "quality_score": 0
            })
            
        deduped = {c["domain"]: c for c in all_companies}
        return list(deduped.values())
